---
functional:
  - Задачи должны решаться на скорость против другого игрока
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - На странице регистрации по почте поле "Nickname" может состоять из латинских букв, цифр и нижнего подчёркивания
  - На странице регистрации по почте поле "Nickname" должен начинаться с латинской буквы
  - На странице регистрации по почте поле "Nickname" не должен начинаться, а так же заканчиваться пробелом
    На странице регистрации по почте поле "Nickname" не может быть два пробела
  - На странице регистрации по почте поле "Password" должен быть от 6 до 16 символов
  - На странице регистрации по почте поле "Password" не должен содержать пробел
  - При создании игры параметрами по умолчанию являются 1 уровень, "with other user", 8 min, random task

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть переведён на английский и русский язык
  - Должна быть страница регистрации и логина
  - Должна быть возможность добавлять в друзья пользователей